INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://www.lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 60, in start
    type(data)
UnboundLocalError: local variable 'data' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:32:43] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in 'thermos.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 60, in start
    type(data)
UnboundLocalError: local variable 'data' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:35:19] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 60, in start
    type(data)
UnboundLocalError: local variable 'data' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:36:26] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 60, in start
    type(data)
UnboundLocalError: local variable 'data' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:38:20] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in 'thermos.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 60, in start
    type(data)
UnboundLocalError: local variable 'data' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:40:08] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 60, in start
    type(data)
UnboundLocalError: local variable 'data' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:41:09] "POST /add HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:41:20] "GET /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 60, in start
    type(data)
UnboundLocalError: local variable 'data' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:41:28] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 60, in start
    type(data)
NameError: global name 'data' is not defined
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:42:14] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:42:57] "POST /add HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:43:24] "GET /add HTTP/1.1" 200 -
ERROR:root:--------EXCEPTION_ERROR--------:www.saviance.com
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 43, in start
    response = opener.open(Company_url)
  File "/home/srinath/anaconda/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/home/srinath/anaconda/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: www.saviance.com
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:43:41] "POST /add HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:43:50] "GET /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /about-us HTTP/1.1" 301 419
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /about-us HTTP/1.1" 200 69598
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us HTTP/1.1" 301 421
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us HTTP/1.1" 200 12624
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:44:23] "POST /add HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 15:45:08] "GET /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 16:01:44] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in 'thermos.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 16:03:01] "POST /add HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 16:05:41] "GET /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /about-us HTTP/1.1" 301 419
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /about-us HTTP/1.1" 200 69598
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us HTTP/1.1" 301 421
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us HTTP/1.1" 200 12624
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 16:05:59] "POST /add HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 16:57:19] "GET /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /about-us HTTP/1.1" 301 419
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /about-us HTTP/1.1" 200 69598
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us HTTP/1.1" 301 421
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us HTTP/1.1" 200 12624
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 16:57:30] "POST /add HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 16:57:59] "GET /no HTTP/1.1" 404 -
INFO:werkzeug: * Detected change in '/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_contactus.py', reloading
ERROR:root:--------EXCEPTION_ERROR--------:saviance.com
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 43, in start
    response = opener.open(Company_url)
  File "/home/srinath/anaconda/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/home/srinath/anaconda/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: saviance.com
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 17:07:43] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in 'thermos.py', reloading
ERROR:root:--------EXCEPTION_ERROR--------:saviance.com
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 43, in start
    response = opener.open(Company_url)
  File "/home/srinath/anaconda/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/home/srinath/anaconda/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: saviance.com
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 17:10:02] "POST /add HTTP/1.1" 200 -
ERROR:root:--------EXCEPTION_ERROR--------:saviance.com
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 43, in start
    response = opener.open(Company_url)
  File "/home/srinath/anaconda/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/home/srinath/anaconda/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: saviance.com
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 17:10:32] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in 'thermos.py', reloading
ERROR:root:--------EXCEPTION_ERROR--------:saviance.com
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 43, in start
    response = opener.open(Company_url)
  File "/home/srinath/anaconda/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/home/srinath/anaconda/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: saviance.com
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 17:11:21] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in 'thermos.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /about-us HTTP/1.1" 200 69598
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us HTTP/1.1" 200 12624
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 17:14:39] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in 'thermos.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /about-us HTTP/1.1" 200 69598
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us HTTP/1.1" 200 12624
INFO:werkzeug:127.0.0.1 - - [09/Dec/2015 17:26:23] "POST /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /about-us HTTP/1.1" 200 69598
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us HTTP/1.1" 200 12624
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 16:52:02] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_contactus.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): licindia.co.in
DEBUG:requests.packages.urllib3.connectionpool:"GET /about_us.htm HTTP/1.1" 200 14723
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): licindia.co.in
DEBUG:requests.packages.urllib3.connectionpool:"GET /phone_helpline.htm HTTP/1.1" 200 16355
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 16:57:52] "POST /add HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 16:58:07] "GET /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 16:58:17] "POST /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 58, in start
    ct_us_text, ctus_url, phone, email= ctus.contactus(all_links, Company_url)
TypeError: 'NoneType' object is not iterable
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 17:08:16] "POST /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 58, in start
    ct_us_text, ctus_url, phone, email= ctus.contactus(all_links, Company_url)
TypeError: 'NoneType' object is not iterable
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 17:09:53] "POST /add HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 17:09:56] "GET /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://www.lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 58, in start
    ct_us_text, ctus_url, phone, email= ctus.contactus(all_links, Company_url)
TypeError: 'NoneType' object is not iterable
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 17:10:09] "POST /add HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py', reloading
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
ERROR:root:--------EXCEPTION_ERROR--------:http://lucideus.com/
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 58, in start
    ct_us_text, ctus_url, phone, email= ctus.contactus(all_links, Company_url)
TypeError: 'NoneType' object is not iterable
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 17:11:16] "POST /add HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 17:11:48] "GET /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /about-us HTTP/1.1" 200 69598
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saviance.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us HTTP/1.1" 200 12624
ERROR:root:--------EXCEPTION_ERROR--------:http://saviance.com
Traceback (most recent call last):
  File "/home/srinath/crayondata/colleagues/interns/to_interns/websiteExtractor/Demo_n_lido_scraper.py", line 58, in start
    ct_us_text, ctus_url, phone, email= ctus.contactus(all_links, Company_url)
TypeError: 'NoneType' object is not iterable
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 17:11:57] "POST /add HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET // HTTP/1.1" 200 24062
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /contact-us/ HTTP/1.1" 200 13821
INFO:werkzeug:127.0.0.1 - - [10/Dec/2015 17:16:26] "POST /add HTTP/1.1" 200 -
INFO:root: --ABOUT US STARTED-- 
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideustech.com
DEBUG:requests.packages.urllib3.connectionpool:"GET / HTTP/1.1" 301 0
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): lucideus.com
DEBUG:requests.packages.urllib3.connectionpool:"GET / HTTP/1.1" 200 35245
INFO:root: --SOCIAL PROFILE STARTED-- 
INFO:root: --CONTACT US STARTED-- 
INFO:werkzeug:127.0.0.1 - - [13/Apr/2016 03:25:41] "POST /add HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2016 03:25:42] "GET /add?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2016 03:25:42] "GET /add?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2016 03:25:42] "GET /add?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2016 03:25:42] "GET /add?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2016 03:25:43] "GET /add?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2016 03:25:43] "GET /add?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
